### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by mohamed-abdul-fattah** [al-amiir/Questions#3]
You mentioned in #1 
```js
const myInit = {
  method: "GET",
  headers: {
    Accept: "image/jpeg",
  },
  mode: "cors",
  cache: "default",
};
```
1. What is CORS?
2. What are the HTTP request and response headers that are used to handle CORS?
3. What are the differences between Simple and Preflighted requests?
4. When to consider CORS while working on a web application frontend?

**Follow up**
Is CORS a browser implementation? In other words, does mobile apps handle CORS? _Try Postman_

**Comment by al-amiir** [comment]
1) CORS : cross origin resource sharing 
When client agent ( like browser ) dealing with servers , servers determine who allowed to make requests , some time requests allowed from same origin , others allow specific domain , others  may allow all domain , CORS is a HTTP header based . 

2) Request headers : headers which client  may use when send  HTTP requests in order to make use of the cross-origin sharing feature 
Headers are : 
-  Origin 
- Access-Control-Request-Method
- Access-Control-Request-Headers

 Response headers : headers which server send back for client requests 
Headers are : 
- Access-Control-Allow-Origin
- Access-Control-Expose-Headers
- Access-Control-Max-Age
- Access-Control-Allow-Credentials
- Access-Control-Allow-Methods
- Access-Control-Allow-Headers

3) Preflight requests : 
When client side  first sends an HTTP request using the OPTIONS method to the resource on the other origin, in order to determine if the actual request is safe to send . 
Simple request : is the request which doesn't use preflight term 

4) Cases using CORS : 
- when sending a form data through POST request 
- When get data through GET method , which sent from another server domain

**Comment by al-amiir** [comment]
In HTTP definition : 
is an application-layer protocol for transmitting hypermedia documents, such as HTML. It was designed for communication between web browsers and web servers, 
So I guess it is a browser implementation , right ?

**Comment by mohamed-abdul-fattah** [comment]
Q4. You have to use CORS while connecting a backend service in another domain. For example the frontend is hosted on http://a.com and the backend service is hosted on http://b.com. This means calling any 3rd party services like facebook from the client-side requires CORS.

**Comment by mohamed-abdul-fattah** [comment]
CORS are a browser implementation. Watch the preflight request that is initiated in the browser network and you'll get that it is called by the browser. Browsers make sure to follow the [same origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) to protect users from malicious attacks.
Try the same request that requires CORS from Postman or any other tool that is not in a browser environment and you'll find that there is no CORS constrains. There are even some [chrome extensions](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en) that disable CORS but they are not safe for non-development usage as they relax the security restrictions (CORS).
